
.PHONY : all

version := 1.0.1

test1 := $(version)
test2 :=
test3 :=
test3 += $(version)
test4 := hello
test4 += 9.999
all :
	@echo "version : [$(version)]"
	@echo "test1 : [$(test1)]"
	@echo "test2 : [$(test2)]"
	@echo "test3 : [$(test3)]"
	@echo "test4 : [$(test4)]"

